/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ddabadi.keuangan.view;

import com.ddabadi.keuangan.App;
import static com.ddabadi.keuangan.App.context;
import com.ddabadi.keuangan.controller.ReportController;
import com.ddabadi.keuangan.dao.HistoryDao;
import com.ddabadi.keuangan.model.History;

import com.ddabadi.keuangan.view.master.MasterJenisTransaksi;
import com.ddabadi.keuangan.view.transaksi.DaftarTransaksi;
import com.ddabadi.keuangan.view.transaksi.TransaksiKeuangan;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 *
 * @author win7
 */
public class FrmMenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuUtama
     */
    
    private HistoryDao historyDao;
    
    public FrmMenuUtama() {
        initComponents();
        historyDao = (HistoryDao)context.getBean("historyDao");
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuJenisTransaksi = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuPengeluaran = new javax.swing.JMenuItem();
        mnuDaftarTransaksi = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuSaldoKas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("  Master  ");

        mnuJenisTransaksi.setText("Jenis Transaksi");
        mnuJenisTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuJenisTransaksiActionPerformed(evt);
            }
        });
        jMenu1.add(mnuJenisTransaksi);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("  Transaksi  ");

        jMenuItem1.setText("Penerimaan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        mnuPengeluaran.setText("Pengeluaran");
        mnuPengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPengeluaranActionPerformed(evt);
            }
        });
        jMenu2.add(mnuPengeluaran);

        mnuDaftarTransaksi.setText("Daftar Transaksi");
        mnuDaftarTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDaftarTransaksiActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDaftarTransaksi);

        jMenuItem3.setText("Kwitansi");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("  Laporan  ");

        mnuSaldoKas.setText("History Kas");
        mnuSaldoKas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaldoKasActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSaldoKas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuJenisTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuJenisTransaksiActionPerformed
        // TODO add your handling code here:
        MasterJenisTransaksi mnuMasterJenisTransaksi = new MasterJenisTransaksi();
        mnuMasterJenisTransaksi.setVisible(true);
    }//GEN-LAST:event_mnuJenisTransaksiActionPerformed

    private void mnuPengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPengeluaranActionPerformed
        // TODO add your handling code here:
        TransaksiKeuangan frmTransaksi = new TransaksiKeuangan("1");
       
        frmTransaksi.setVisible(true);
    }//GEN-LAST:event_mnuPengeluaranActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        TransaksiKeuangan frmTransaksi = new TransaksiKeuangan("0");
     
        frmTransaksi.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnuSaldoKasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaldoKasActionPerformed
        // TODO add your handling code here:
        List<History> histories = historyDao.getByDate(new Date()) ;
        Map parameter = new HashMap();
        parameter.put("h1", "judul1");
        parameter.put("h2", "judul1");
        parameter.put("h3", "judul1");
        parameter.put("h4", "judul1");
        
        ReportController.previewReport("laporan/RptHistory.jasper", parameter, 
                histories, "History");
    }//GEN-LAST:event_mnuSaldoKasActionPerformed

    private void mnuDaftarTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDaftarTransaksiActionPerformed
        // TODO add your handling code here:
        DaftarTransaksi daftarTransaksi = new DaftarTransaksi();
        daftarTransaksi.setVisible(true);
    }//GEN-LAST:event_mnuDaftarTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem mnuDaftarTransaksi;
    private javax.swing.JMenuItem mnuJenisTransaksi;
    private javax.swing.JMenuItem mnuPengeluaran;
    private javax.swing.JMenuItem mnuSaldoKas;
    // End of variables declaration//GEN-END:variables
}
