/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ddabadi.keuangan.view.transaksi;

import static com.ddabadi.keuangan.App.context;
import com.ddabadi.keuangan.controller.ReportController;
import com.ddabadi.keuangan.dao.KwitansiDao;
import com.ddabadi.keuangan.dao.ParamsDao;
import com.ddabadi.keuangan.dao.TransaksiHdDao;
import com.ddabadi.keuangan.dto.SlipDto;
import com.ddabadi.keuangan.model.Params;
import com.ddabadi.keuangan.model.TransaksiHd;
import com.ddabadi.keuangan.utility.Rupiah;
import java.awt.Component;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author win7
 */
public class DaftarTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form DaftarTransaksi
     */
    
    private final TransaksiHdDao transaksiHdDao;    
    private final ParamsDao paramsDao;
    
    
    private DefaultTableModel tableModel;
    
    public DaftarTransaksi() {
        initComponents();
        setLocationRelativeTo(null);
        transaksiHdDao = (TransaksiHdDao) context.getBean("transaksiHdDao");
        paramsDao =(ParamsDao) context.getBean("paramsDao");
        
        setTableModel();
        isiTable();
        tglProses.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateTime1 = new org.joda.time.DateTime();
        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDaftar = new javax.swing.JTable();
        btnPreview = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        tglProses = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblDaftar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDaftar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblDaftar);

        btnPreview.setText("preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        tglProses.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tglProses.setDateFormatString("dd - MMM - yyyy");
        tglProses.setFocusable(false);
        tglProses.setNextFocusableComponent(tblDaftar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tglProses, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tglProses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPreview)
                        .addComponent(btnExit)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        int pilih = tblDaftar.getSelectedRow();        
        
        try{
            Params params = paramsDao.getParams();
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-yyyy");
                                    
            Long idTransaksi = Long.parseLong(tableModel.getValueAt(pilih, 0).toString());
            TransaksiHd transaksiHd = transaksiHdDao.getById(idTransaksi);            
            
            String rp=Rupiah.convert( transaksiHd.getTotal().intValue());
            SlipDto slipDto = new SlipDto();
            slipDto.setId(idTransaksi);
            slipDto.setJenisTransaksi(transaksiHd.getJenisTransaksi().getNamaJenisTransaksi());
            slipDto.setNoTransaksi(transaksiHd.getNoTransaksi());
            slipDto.setTipeTransaksi(transaksiHd.getTipeTransaksi().toString());
            slipDto.setTerbilang("# " + rp + "Rupiah #");
            slipDto.setTotal(transaksiHd.getTotal());
            slipDto.setTanggal(sdf.format(transaksiHd.getTanggal() ));
            slipDto.setKeterangan(transaksiHd.getKeterangan());
            
            List<SlipDto> lists = new ArrayList<>();
            lists.add(slipDto);
            
            Map parameter = new HashMap();
            parameter.put("h1", params.getH1().trim());
            parameter.put("h2", params.getH2().trim());
            parameter.put("h3", params.getH3().trim());
            parameter.put("h4", params.getH4().trim());
        
            ReportController.previewReport("laporan/buktiSlip.jasper", parameter,lists, "Slip");
            
        }catch(Exception e){
            e.printStackTrace();
            System.out.println(e.getMessage());
        }
        
        
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void setTableModel(){
        tableModel= new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                //all cells false
                return false;
            }
        };
        tblDaftar.setModel(tableModel);        
        tableModel.addColumn("Id");
        tableModel.addColumn("No Transaksi");
        tableModel.addColumn("Jenis");
        tableModel.addColumn("tipe");
        tableModel.addColumn("total");
        tableModel.addColumn("approved");
        tableModel.addColumn("cancel");
        
        
        
        
        tblDaftar.getColumnModel().getColumn(4).setCellRenderer(new DecimalFormatRenderer() );
        //alignment 
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        tblDaftar.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );               
        
        tblDaftar.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        tblDaftar.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblDaftar.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblDaftar.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblDaftar.getColumnModel().getColumn(3).setPreferredWidth(100);
        tblDaftar.getColumnModel().getColumn(4).setPreferredWidth(100);
        tblDaftar.getColumnModel().getColumn(5).setPreferredWidth(50);                
        
        
        
    }
    
    private void isiTable(){
        tableModel.getDataVector().removeAllElements();
        tableModel.fireTableDataChanged();                
        
        TransaksiHd  transaksiHd  = new TransaksiHd();
        Iterator iterator = transaksiHdDao.getTransaksiByDate(new Date()).iterator();
        while(iterator.hasNext()){
            Object[] o = new Object[7];
            transaksiHd= ((TransaksiHd) iterator.next());
            o[0]= transaksiHd.getId();
            o[1]= transaksiHd.getNoTransaksi();
            o[2]= transaksiHd.getJenisTransaksi().getNamaJenisTransaksi();
            o[3]= transaksiHd.getTipeTransaksi();
            o[4]= transaksiHd.getTotal();
            o[5]= transaksiHd.getIsApprove();
            o[6]= transaksiHd.getIsCancel();
            tableModel.addRow(o);    
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarTransaksi().setVisible(true);
            }
        });
    }

    static class DecimalFormatRenderer extends DefaultTableCellRenderer {
		private static final DecimalFormat formatter = new DecimalFormat( "#.00" );
 
		public Component getTableCellRendererComponent(
			JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                        // First format the cell value as required

			value = formatter.format((Number)value);

                        // And pass it on to parent class 

			return super.getTableCellRendererComponent(
				table, value, isSelected, hasFocus, row, column );
		} 
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPreview;
    private org.joda.time.DateTime dateTime1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDaftar;
    private com.toedter.calendar.JDateChooser tglProses;
    // End of variables declaration//GEN-END:variables
}
